### ISSUE TITLE
Email search not working

### ISSUE THREAD

**Issue by makoto** [ensdomains/short-name-claims-app#2]
<img width="784" alt="Screenshot 2019-07-04 at 12 07 13" src="https://user-images.githubusercontent.com/2630/60662575-a984b980-9e54-11e9-8a5b-47754aacce1f.png">

**Comment by Arachnid** [comment]
I've enhanced the search, so you can now use 'email:', 'owner:', 'status:', 'dnsname:' and 'name:' operators.
