### ISSUE TITLE
value missmatch

### ISSUE THREAD

**Issue by ligi** [ensdomains/short-name-claims-app#5]
![image](https://user-images.githubusercontent.com/111600/62175072-8b6b8580-b33c-11e9-91cb-6bb1045d3f7b.png)

**Comment by Arachnid** [comment]
As mentioned elsewhere - we add a percentage to account for exchange rate variation; the difference is refunded.

**Comment by ligi** [comment]
yes - opened the issue before seeing your reply on twitter. But still think this is an issue - not to change the values but to make this more transparent. Did not see this in the claim process.
